version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data
    depends_on:
      - backend1
      - backend2

  backend1:
    build: ./backend
    environment:
      INSTANCE_NAME: backend-1
    volumes:
      - ./data:/home/emrecan/home/prod-monitoring/data

  backend2:
    build: ./backend
    environment:
      INSTANCE_NAME: backend-2
    volumes:
      - ./data:/home/emrecan/home/prod-monitoring/data

