services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2

  backend1:
    build: .
    environment:
      INSTANCE_NAME: backend-1

  backend2:
    build: .
    environment:
      INSTANCE_NAME: backend-2

